a_crud/a_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('b_data_crud.urls')),
]

a_crud/b_data_crud/urls.py
# =========================== MEMBUAT URLS AGAR MUDAH DALAM PEMANGGILAN ==================


from django.urls import path
from . import views                     # Harus di isi 

urlpatterns = [
    path('',views.menu_data, name="menu-data-page"),                 # penulisane name juga harus benar harus inputkan nama htmlnya
    path('data', views.table_data_1, name="data-1-page"),  # penulisane name juga harus benar harus inputkan nama htmlnya
    
    path('data_2', views.table_data_2, name="data-2-page"),  # penulisane name juga harus benar harus inputkan nama htmlnya
    
    
    # get a fungsi add data
    path('tambah', views.add_data, name="add-data-page"),
    path('tambah_2', views.add_data_2, name="add-data-2-page"),
    
    path('delete/<int:id>', views.delete_data, name="delete-data"),  # penulisane name juga harus benar harus inputkan nama htmlnya
    
    path('delete_2/<int:id>', views.delete_data_2, name="delete-data-2"),  # penulisane name juga harus benar harus inputkan nama htmlnya
    
    # get a fungsi edit data
    path('edit/<int:id>', views.edit_data, name="edit-data-page"),
    path('edit_2/<int:id>', views.edit_data_2, name="edit-data-page"),
    #path('edit/<int:id>',views.edit, name="mahasiswa_edit"),   

    # Memanggil fungsi data print
    path('print', views.data_print, name="print-data-page"),

     path('data/create/', views.data_create, name='data_create'),
    path('data/list/', views.data_list, name='data_list'),
]

a_crud/b_data_crud/models.py
from django.db import models
import joblib
from django.core.validators import MaxValueValidator, MinValueValidator
from sklearn.tree import DecisionTreeClassifier

# Create your models here.

# create a class data_1 model with id , name , descriptions
class data_1(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class data_2(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100, null=True)
    description = models.CharField(max_length=200)


    def __str__(self):
        return self.name

class data_mahasiwa(models.Model):

    jk = (
        ('L', 'Laki-Laki'),
        ('P', 'Perempuan'),
    )
    id = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=100)
    jenis_kelamin = models.CharField(max_length = 150, choices=jk)
    nim = models.CharField(max_length=100)
    fakultas = models.CharField(max_length=100)
    jurusan = models.CharField(max_length=100)
    prodi = models.CharField(max_length=100)
    nilai_sikap = models.IntegerField()
    nilai_uts   = models.IntegerField()
    nilai_uas   = models.IntegerField()

    # sum nilai_sikap, nilai_uts
    def nilai_akhir(self):
        return self.nilai_sikap + self.nilai_uts + self.nilai_uas
    # nilai akhir / jumlah mata kuliah
    def nilai_akhir_per_mata_kuliah(self):
        return self.nilai_akhir() / 3
    def __str__(self):
        return self.nama

# Create your models here.
GENDER = (
    (0, 'Terlentang'),
    (1, 'Berdiri'),
)
 
class Data(models.Model):
    name = models.CharField(max_length=100, null=True)
    age = models.PositiveIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)], null=True)
    height = models.PositiveIntegerField(null=True)
    sex = models.PositiveIntegerField(choices=GENDER, null=True)
    predictions = models.CharField(max_length=100, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        ml_model = joblib.load('ml_model/ml_sport_model.joblib')
        self.predictions = ml_model.predict(
            [[self.age, self.height, self.sex]])
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.name

a_crud/b_data_crud/forms.py
# =========================== MEMBUAT FORM UNTUK LOGIN ==================

# Module dalam melakukan memanggilan form

from django import forms

from .models import data_1, data_2, Data       # Memanggil models yang sudah dibuat

# Membuat class untuk menentukan form mahasisa

class Data_1Form(forms.ModelForm):
    class Meta :
        model = data_1
        fields = ('name','description')


class Data_2Form(forms.ModelForm):
    class Meta :
        model = data_2
        fields = ('name','description','email')

class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = ['name', 'age', 'height', 'sex']

a_crud/b_data_crud/views.py
from django.shortcuts import render, redirect

# import messages
from django.contrib import messages

# Create your views here.

# Membuat Fungsi Menampilkan Menu Data
def menu_data(request):
    context = {
        'data' : 'Menu Data'
    }
    return render(request, 'b_data_crud/menu_data.html', context)

# Mengambil Table Data_1 dari models
from .models import data_1
def table_data_1(request):
    data_tampil_1 = data_1.objects.all()
    context = {
        'data_1' : data_tampil_1
        }
    return render(request, 'b_data_crud/data_1.html', context)

from .models import data_2
def table_data_2(request):
    data_tampil_2 = data_2.objects.all()
    context = {
        'data_2' : data_tampil_2
        }
    return render(request, 'b_data_crud/data_2.html', context)

def delete_data_2(request, id):
    delete_data_2= data_2.objects.get(id=id).delete()
    messages.success(request, 'Data 2 berhasil dihapus')
    return redirect('data-2-page')


# Membuat Fungsi Delete berdasarkan id
def delete_data(request, id):
    delete_data = data_1.objects.get(id=id).delete()
    # create a messages
    messages.success(request, 'Data berhasil dihapus')
    return redirect('data-1-page')



# Membuat tambah Data dari forms
from .forms import Data_1Form
def add_data(request):
    form = Data_1Form()
    if request.method == 'POST':
        form = Data_1Form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data berhasil ditambahkan')
            return redirect('data-1-page')
    else :
        form = Data_1Form()
    context = {
        'form' : form
        }
    return render(request, 'b_data_crud/tambah_data_1.html', context)

from .forms import Data_2Form
def add_data_2(request):
    form = Data_2Form()
    if request.method == 'POST':
        form = Data_2Form(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data berhasil ditambahkan')
            return redirect('data-2-page')
    else :
        form = Data_2Form()
    context = {
        'form' : form
        }
    return render(request, 'b_data_crud/tambah_data_2.html', context)



# Membuat Edit data
from .forms import Data_1Form
def edit_data(request, id): 
    data_1_edit = data_1.objects.get(id=id)
    form = Data_1Form(instance=data_1_edit)
    if request.method == 'POST':
        form = Data_1Form(request.POST, instance=data_1_edit)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data berhasil diedit')
            return redirect('data-1-page')
    context = {
        'form' : form,
        'data_1_edit' : data_1_edit
        }
    return render(request, 'b_data_crud/edit_data_1.html', context)

# Membuat Edit data
from .forms import Data_2Form
def edit_data_2(request, id): 
    data_2_edit = data_2.objects.get(id=id)
    form = Data_2Form(instance=data_2_edit)
    if request.method == 'POST':
        form = Data_2Form(request.POST, instance=data_2_edit)
        if form.is_valid():
            data_2 = form.save(commit=False)
            data_2.save()
            messages.success(request, 'Data berhasil diedit')
            return redirect('data-2-page')
    context = {
        'form' : form,
        'data_2_edit' : data_2_edit
        }
    return render(request, 'b_data_crud/edit_data_2.html', context)


# Membuat fungsi data 
from . models import data_mahasiwa
def data_print(request):
    data_print = data_mahasiwa.objects.all()

    for dataku in data_print:
        dataku.rata_rata = dataku.nilai_akhir_per_mata_kuliah()
    context = {
        'dataku' : data_print,
    }
    return render(request, 'b_data_crud/data_print.html', context)


from .forms import DataForm
from .models import Data
from django.shortcuts import render, redirect
import joblib
import pickle
import json

def data_create(request):
    if request.method == 'POST':
        # Proses pengisian form dan prediksi
        # ...

        # Load model dari joblib
        ml_model = joblib.load('ml_model/ml_sport_model.joblib')

        # Konversi model menjadi format JSON
        json_model = json.dumps(ml_model, cls=JoblibEncoder)

        # Simpan data ke database
        form.save()

        return redirect('data_list')  # Ganti 'data_list' dengan URL yang sesuai
    else:
        form = DataForm()
    
    return render(request, 'b_data_crud/data_create.html', {'form': form})

class JoblibEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, bytes):
            return {'__class__': 'bytes', '__value__': list(obj)}
        return super().default(obj)


def data_list(request):
    data = Data.objects.all().order_by('-date')
    return render(request, 'b_data_crud/data_list.html', {'data': data})

a_crud/b_data_crud/templates/b_data_crud/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>CRUD DEWA</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">APP</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'menu-data-page' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Data_1</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Data_2</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}

      




      {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

a_crud/b_data_crud/templates/b_data_crud/data_1.html
{% extends 'b_data_crud/base.html' %}


{% block content %}

<div class="container mt-4">

    <div class="card">
        <div class="card-body">
            <div class="row">
                <a class="btn btn-secondary" href="{% url 'add-data-page' %}"> Tambah Data </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Deskripsi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Lakukan looping disini -->
                        {% for data in data_1 %}
                        <tr>
                            <td>{{data.id}}</td>
                            <td>{{data.name}}</td>
                            <td>{{data.description }}</td>
                            <td>
                                <a class="btn btn-danger" onclick="elementdata({{data.id}})" href="#">Hapus Data</a>
                                <a class="btn btn-primary"  href="edit/{{data.id}}">Edit Data</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}

    {% for m in messages %}

    <script>
        Swal.fire({
            'title': '',
            'text': '{{m}}',
            'icon': 'success',
        })
    </script>

    {% endfor %}


{% endif %}
{% for data in data_1 %}
<script>
    function elementdata(id){
        Swal.fire({
            'title': 'Hapus Data',
            'text': 'Aapakah anda ingin menghapus {{data.name}} ?',
            'icon': 'question',
            'showCancelButton': true,
            'confirmButtonColor': '#dc3545',
            'confirmButtonText': 'Hapus',
            'reverseButtons':true,
            'cancelButtonText': 'Batal',

        })
        .then(function(result){
            if (result.isConfirmed) {
                window.location.href = "delete/"+id
                }
            })
        }
        
</script>
{% endfor %}

{% endblock content %}

a_crud/b_data_crud/templates/b_data_crud/data_2.html
{% extends 'b_data_crud/base.html' %}

{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <a class="btn btn-secondary" href="{% url 'add-data-2-page' %}"> Tambah Data </a>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Nama</th>
                            <th scope="col">Deskripsi</th>
                            <th scope="col">Email</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Lakukan looping disini -->
                        {% for data in data_2 %}
                        <tr>
                            <td>{{data.id}}</td>
                            <td>{{data.name}}</td>
                            <td>{{data.description }}</td>
                            <td>{{data.email }}</td>
                            <td>
                                <a class="btn btn-danger" onclick="elementdata({{data.id}})" href="#">Hapus Data</a>
                                <a class="btn btn-primary" href="edit_2/{{data.id}}">Edit Data</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% if messages %}

    {% for m in messages %}

    <script>
        Swal.fire({
            'title': '',
            'text': '{{m}}',
            'icon': 'success',
        })
    </script>

    {% endfor %}


{% endif %}
{% for data in data_2 %}
<script>
    function elementdata(id){
        Swal.fire({
            'title': 'Hapus Data',
            'text': 'Aapakah anda ingin menghapus {{data.name}} ?',
            'icon': 'question',
            'showCancelButton': true,
            'confirmButtonColor': '#dc3545',
            'confirmButtonText': 'Hapus',
            'reverseButtons':true,
            'cancelButtonText': 'Batal',

        })
        .then(function(result){
            if (result.isConfirmed) {
                window.location.href = "delete_2/"+id
                }
            })
        }
        
</script>
{% endfor %}
{% endblock content %}

a_crud/b_data_crud/templates/b_data_crud/data_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testing</title>
</head>
<body>
    <!-- data_create.html -->

<form method="post">
    {% csrf_token %}
    <div class="mb-3">
      <label for="id_name" class="form-label">Nama</label>
      {{ form.name }}
    </div>
    <div class="mb-3">
      <label for="id_age" class="form-label">Umur</label>
      {{ form.age }}
    </div>
    <div class="mb-3">
      <label for="id_height" class="form-label">Tinggi</label>
      {{ form.height }}
    </div>
    <div class="mb-3">
      <label for="id_sex" class="form-label">Jenis Kelamin</label>
      {{ form.sex }}
    </div>
    <div id="resultDiv" style="display: none;">
      <h3>Hasil Prediksi:</h3>
      <p>{{ predictions }}</p>
      <button type="button" onclick="saveData()">Simpan</button>
      <button type="button" onclick="cancelData()">Batal</button>
    </div>
    <div id="buttonDiv">
      <button type="button" onclick="showResult()">Lihat Hasil</button>
      <button type="submit">Simpan</button>
      <button type="button" onclick="cancelData()">Batal</button>
    </div>
  </form>
  
  <script>
    function showResult() {
      // Mendapatkan nilai form
      var age = document.getElementById("id_age").value;
      var height = document.getElementById("id_height").value;
      var sex = document.getElementById("id_sex").value;
  
      // Kirim data ke endpoint prediksi melalui AJAX
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "/predict/", true);
      xhr.setRequestHeader("Content-Type", "application/json");
      xhr.onreadystatechange = function () {
        if (xhr.readyState === 4 && xhr.status === 200) {
          // Tampilkan hasil prediksi
          var resultDiv = document.getElementById("resultDiv");
          resultDiv.style.display = "block";
          resultDiv.innerHTML = "<h3>Hasil Prediksi:</h3>" + xhr.responseText;
        }
      };
      var data = JSON.stringify({ age: age, height: height, sex: sex });
      xhr.send(data);
    }
  
    function saveData() {
      // Submit form untuk menyimpan data
      document.querySelector("form").submit();
    }
  
    function cancelData() {
      // Mengalihkan halaman kembali ke form awal
      window.location.href = "{% url 'data_create' %}";
    }
  </script>
  
</body>
</html>

a_crud/b_data_crud/templates/b_data_crud/data_list.html
{% for item in data %}
  <div>
    <p>Nama: {{ item.name }}</p>
    <p>Umur: {{ item.age }}</p>
    <p>Tinggi: {{ item.height }}</p>
    <p>Jenis Kelamin: {{ item.sex }}</p>
    <p>Hasil Prediksi: {{ item.predictions }}</p>
  </div>
  <hr>
{% empty %}
  <p>Tidak ada data yang tersedia.</p>
{% endfor %}

a_crud/b_data_crud/templates/b_data_crud/data_print.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">

    <title>CRUD DEWA</title>
</head>

<body>
    <div class="container mt-4">
        <div class="card">
            <div class="card-body">
                <div class="row">

                    <table id="example" class="display nowrap" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Jenis Kelamin</th>
                                <th>NIM</th>
                                <th>Fakultas</th>
                                <th>Jurusan</th>
                                <th>Prodi</th>
                                <th>Nilai Sikap</th>
                                <th>Nilai UTS</th>
                                <th>Nilai UAS</th>
                                <th>Nilai Rata-Rata</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Jenis Kelamin</th>
                                <th>NIM</th>
                                <th>Fakultas</th>
                                <th>Jurusan</th>
                                <th>Prodi</th>
                                <th>Nilai Sikap</th>
                                <th>Nilai UTS</th>
                                <th>Nilai UAS</th>
                                <th>Nilai Rata-Rata</th>
                            </tr>
                        </tfoot>
                        {% for data in dataku %}
                        <tbody>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ data.nama }}</td>
                                <td>{{ data.jenis_kelamin }}</td>
                                <td>{{ data.nim }}</td>
                                <td>{{ data.fakultas }}</td>
                                <td>{{ data.jurusan }}</td>
                                <td>{{ data.prodi }}</td>
                                <td>{{ data.nilai_sikap }}</td>
                                <td>{{ data.nilai_uts }}</td>
                                <td>{{ data.nilai_uas }}</td>
                                <td>{{ data.rata_rata|floatformat:2 }}</td>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });
    </script>
</body>

</html>

a_crud/b_data_crud/templates/b_data_crud/edit_data_1.html
{% extends 'b_data_crud/base.html' %}

{% block content %}
{% load widget_tweaks %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Nama</label>
                      {% render_field form.name placeholder=form.name.label class+="form-control"  %}
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Deskripsi</label>
                      {% render_field form.description placeholder=form.description.label class+="form-control"  %}
                    </div>
                    <input type="submit" class="btn btn-primary"></input>
                    <a href="{% url 'data-1-page' %}" class="btn btn-danger">Kembali</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

a_crud/b_data_crud/templates/b_data_crud/edit_data_2.html
{% extends 'b_data_crud/base.html' %}

{% block content %}
{% load widget_tweaks %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Nama</label>
                      {% render_field form.name placeholder=form.name.label class+="form-control"  %}
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Deskripsi</label>
                      {% render_field form.description placeholder=form.description.label class+="form-control"  %}
                    </div>
                    <input type="submit" class="btn btn-primary"></input>
                    <a href="{% url 'data-2-page' %}" class="btn btn-danger">Kembali</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

a_crud/b_data_crud/templates/b_data_crud/menu_data.html
{% extends 'b_data_crud/base.html' %}

{% block content %}

<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Menu Data 1</h5>
                            <a href="{% url 'data-1-page' %}" class="btn btn-primary">Lihat Data</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Menu Data 2</h5>
                            <a href="{% url 'data-2-page' %}" class="btn btn-primary">Lihat Data</a>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Menu Data Print</h5>
                            <a href="{% url 'data_create' %}" class="btn btn-primary">Prediksi Coba</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

a_crud/b_data_crud/templates/b_data_crud/tambah_data_1.html
{% extends 'b_data_crud/base.html' %}

{% block content %}
{% load widget_tweaks %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Nama</label>
                      {% render_field form.name placeholder=form.name.label class+="form-control"  %}
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Deskripsi</label>
                      {% render_field form.description placeholder=form.description.label class+="form-control"  %}
                    </div>
                    <input type="submit" class="btn btn-primary"></input>
                    <a href="{% url 'data-1-page' %}" class="btn btn-danger">Kembali</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}